name: Generate GitHub Contribution Graph Artwork

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate contribution graph SVG
        uses: jasineri/gitartwork@v1
        with:
          user_name: Rishp-3
          text: RISHABH

      - name: Push changes
        uses: jasineri/simple-push-action@v1
