name: Waka Readme

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_7e71a169-6240-42e2-8757-1fbaba797112 }}
